### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by ipolikarpov** [bigperson/modulpos-php-api-client#7]
Месяц назад в тестовом режиме все работало нормально. 
Сейчас обновил пакет, получил боевые доступы, включил нормальный режим и вот:

```
PHP Fatal error:  Uncaught Guzzle\Http\Exception\ClientErrorResponseException: Client error response
[status code] 400
[reason phrase] Bad Request
[url] https://service.modulpos.ru/api/fn/v1/doc in /[...]/vendor/guzzle/http/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
#0 /[...]/vendor/guzzle/http/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#1 /[...]/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /[...]/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Co in /[...]/vendor/guzzle/http/Guzzle/Http/Exception/BadResponseException.php on line 43
```

**Comment by ipolikarpov** [comment]
И вот еще что выдавал композер при обновлении. Я не знаю, возможно на это стоит обратить внимание.
```
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
```

**Comment by bigperson** [comment]
@liggth Обновитесь до версии ^1.0 должно все заработать

**Comment by ipolikarpov** [comment]
Обновил, вот что установлено:
```
automattic/woocommerce            2.0.1   A PHP wrapper for the WooCommerce REST API
bigperson/modulpos-php-api-client 1.0.1   PHP client for modulpos API Fiscal Service
guzzle/guzzle                     v3.9.3  PHP HTTP client. This library is deprecated in favor of https://packagist.org/packages/guzzlehttp/guzzle
phpmailer/phpmailer               v6.0.6  PHPMailer is a full-featured email creation and transfer class for PHP
symfony/event-dispatcher          v2.8.49 Symfony EventDispatcher Component
```

$client->sendCheck() та же фигня:
```
PHP Fatal error:  Uncaught Guzzle\Http\Exception\ClientErrorResponseException: Client error response
[status code] 400
[reason phrase] Bad Request
[url] https://service.modulpos.ru/api/fn/v1/doc in /vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
#0 /vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#1 /vendor/symfony/event-dispatcher/EventDispatcher.php(184): Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Obje in /vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php on line 43
```

**Comment by bigperson** [comment]
@ipolikarpov Судя по всему у вас ошибка в параметрах которые вы передаете.
Приведите пример как вызываете

**Comment by ipolikarpov** [comment]
Если коротко, то:
```
$client = new \Bigperson\ModulposApiClient\Client($mkConfig['mkLogin'], $mkConfig['mkPassword'], $mkConfig['mkTestMode']);
$printReceipt = false; // Печатать ли чек на кассе
$result = $client->sendCheck($mkOrder, NULL, $printReceipt);
```

Само собой, до этого создаю заказ, добавляю в него товары, платеж. Не добавляю только кассира.

**Comment by bigperson** [comment]
@ipolikarpov Сделайте дамп параметров запроса перед отправкой и проверьте все ли соответсвует документации модуль кассы

**Comment by ipolikarpov** [comment]
Проверил, действительно по ценам и сумме та мне совпадали данные. Подправил – заработало.
Спасибо большое за помощь и сам пакет.
